var game = {
    "action": "turn",
    "map": {
        "paths": [
            { "to": 2, "from": 1 },
            { "to": 3, "from": 1 },
            { "to": 3, "from": 2 },
            { "to": 4, "from": 2 },
            { "to": 4, "from": 3 },
            { "to": 6, "from": 5 },
            { "to": 7, "from": 5 },
            { "to": 7, "from": 6 },
            { "to": 8, "from": 6 },
            { "to": 8, "from": 7 },
            { "to": 10, "from": 9 },
            { "to": 11, "from": 9 },
            { "to": 11, "from": 10 },
            { "to": 12, "from": 10 },
            { "to": 12, "from": 11 },
            { "to": 14, "from": 13 },
            { "to": 15, "from": 13 },
            { "to": 15, "from": 14 },
            { "to": 16, "from": 14 },
            { "to": 16, "from": 15 },
            { "to": 19, "from": 4 },
            { "to": 23, "from": 4 },
            { "to": 20, "from": 8 },
            { "to": 23, "from": 8 },
            { "to": 19, "from": 12 },
            { "to": 24, "from": 12 },
            { "to": 24, "from": 16 },
            { "to": 20, "from": 16 },
            { "to": 19, "from": 17 },
            { "to": 20, "from": 18 },
            { "to": 17, "from": 3 },
            { "to": 17, "from": 10 },
            { "to": 18, "from": 7 },
            { "to": 18, "from": 15 },
            { "to": 21, "from": 6 },
            { "to": 21, "from": 2 },
            { "to": 22, "from": 11 },
            { "to": 23, "from": 21 },
            { "to": 24, "from": 22 },
            { "to": 22, "from": 14 }
        ],
        "nodes": [
            { "type": "city", "id": 1 },
            { "type": "city", "id": 2 },
            { "type": "city", "id": 3 },
            { "type": "city", "id": 4 },
            { "type": "city", "id": 5 },
            { "type": "city", "id": 6 },
            { "type": "city", "id": 7 },
            { "type": "city", "id": 8 },
            { "type": "city", "id": 9 },
            { "type": "city", "id": 10 },
            { "type": "city", "id": 11 },
            { "type": "city", "id": 12 },
            { "type": "city", "id": 13 },
            { "type": "city", "id": 14 },
            { "type": "city", "id": 15 },
            { "type": "city", "id": 16 },
            { "type": "node", "id": 17 },
            { "type": "node", "id": 18 },
            { "type": "node", "id": 19 },
            { "type": "node", "id": 20 },
            { "type": "node", "id": 21 },
            { "type": "node", "id": 22 },
            { "type": "node", "id": 23 },
            { "type": "node", "id": 24 }
        ], "types": [
            { "soldiers_per_turn": 1, "points": 1, "name": "city" },
            { "soldiers_per_turn": 0, "points": 0, "name": "node" }
        ]
    },
    "infos": {
        "directed": false,
        "number_of_players": 2,
        "current_turn": 2,
        "time_limit_per_turn": 5000,
        "player_id": 0,
        "maximum_number_of_turns": 50,
        "game_id": "6f7d0c46-341b-11e3-a10b-139b870c7992"
    },
    "state": [
        { "player_id": 0, "node_id": 1, "number_of_soldiers": 1 },
        { "player_id": 0, "node_id": 2, "number_of_soldiers": 4 },
        { "player_id": 0, "node_id": 3, "number_of_soldiers": 3 },
        { "player_id": null, "node_id": 4, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 5, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 6, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 7, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 8, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 9, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 10, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 11, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 12, "number_of_soldiers": 0 },
        { "player_id": 1, "node_id": 13, "number_of_soldiers": 1 },
        { "player_id": 1, "node_id": 14, "number_of_soldiers": 3 },
        { "player_id": 1, "node_id": 15, "number_of_soldiers": 4 },
        { "player_id": null, "node_id": 16, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 17, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 18, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 19, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 20, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 21, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 22, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 23, "number_of_soldiers": 0 },
        { "player_id": null, "node_id": 24, "number_of_soldiers": 0 }
    ]
}
